### ISSUE TITLE
Shell Script

### ISSUE THREAD

**Issue by explosive2005** [avafinger/nanopi-a64-firmware#7]
The shell script sudo (./burn_sdcard.sh /dev/sdc) is not available in the nanopi a64 repositiory. Thank you for your hard work.

**Comment by avafinger** [comment]
Oops, now is there.
please see if it works: https://github.com/avafinger/nanopi-a64-firmware/commit/32f9ea0773eeae47f9e2fac973c5090affb407c0

**Comment by explosive2005** [comment]
When using the new shell script "burn_sdcard_v2.sh" the script can not find the file "u-boot-nanopia64.bin", I tried "u-boot-nanopi-a64.bin", "u-boot-nanopi64.bin", and "ub-nanopi-a64.bin" and none of them work. When looking at the serial terminal the a64 cannot find the bootloader.

**Comment by avafinger** [comment]
Fixed.

Please, update and try again. Tested myself and it is OK now.
Thanks

Edited: If it does not boot, please attach the log!

**Comment by explosive2005** [comment]
It is still not booting, here is the output from the Putty:

`=~=~=~=~=~=~=~=~=~=~=~= PuTTY log 2017.10.30 17:35:37 =~=~=~=~=~=~=~=~=~=~=~=
:
sunxi#
sunxi#
sunxi#
sunxi#
sunxi#HELLO! BOOT0 is starting!
boot0 commit : 045061a8bb2580cb3fa02e301f52a015040c158f
 
boot0 version : 4.0.0
set pll start
set pll end
rtc[0] value = 0x00000000
rtc[1] value = 0x00000000
rtc[2] value = 0x00000000
rtc[3] value = 0x00000000
rtc[4] value = 0x00000000
rtc[5] value = 0x00000000
DRAM driver version: V1.1
rsb_send_initseq: rsb clk 400Khz -> 3Mhz
PMU: AXP81X
ddr voltage = 1500 mv
DRAM Type = 3 (2:DDR2,3:DDR3,6:LPDDR2,7:LPDDR3)
DRAM clk = 672 MHz
DRAM zq value: 003b3bbb
DRAM single rank full DQ OK
DRAM size = 1024 MB
DRAM init ok
dram size =1024
card boot number = 0, boot0 copy = 0
card no is 0
sdcard 0 line count 4
[mmc]: mmc driver ver 2015-05-08 20:06
[mmc]: sdc0 spd mode error, 2
[mmc]: Wrong media type 0x00000000
[mmc]: ***Try SD card 0***
[mmc]: HSSDR52/SDR25 4 bit
[mmc]: 50000000 Hz
[mmc]: 30436 MB
[mmc]: ***SD/MMC 0 init OK!!!***
sdcard 0 init ok
The size of uboot is 000e4000.
sum=e4887dd4
src_sum=e4887dd4
Succeed in loading uboot from sdmmc flash.
boot0: start load other image
boot0: Loading BL3-1
Loading file 0 at address 0x40000000,size 0x0000a200 success
boot0: Loading scp
Loading file 2 at address 0x00040000,size 0x00019a00 success
set arisc reset to de-assert state
Ready to disable icache.
Jump to secend Boot.
r=Q%
é  Configuring SPC Controller
NOTICE:  BL3-1: v1.0(debug):3cdc5c3
NOTICE:  BL3-1: Built : 15:26:02, Oct 24 2017
INFO:    BL3-1: Initializing runtime services
INFO:    BL3-1: Preparing for EL3 exit to normal world
INFO:    BL3-1: Next image address = 0x4a000000
INFO:    BL3-1: Next image spsr = 0x1d3


U-Boot 2014.07-A64-00004-g6f37e5c-dirty (Oct 24 2017 - 15:25:20) Allwinner Technology 

uboot commit : 6f37e5cf6a65b0b10455d12dbd631effabe765ec
 
rsb: secure monitor exist
[      0.376]pmbus:   ready
[      0.378][ARISC] :arisc initialize
[      0.712][ARISC] :arisc_dvfs_cfg_vf_table: support only one vf_table
[SCP] :sunxi-arisc driver begin startup 2
[SCP] :arisc_para size:1a8
[SCP] :arisc version: [v0.1.76]
[SCP] :sunxi-arisc driver v1.10 is starting
[      0.841][ARISC] :sunxi-arisc driver startup succeeded
[      0.874]PMU: AXP81X
[      0.876]PMU: AXP81X found
bat_vol=0, ratio=0
[      0.883]PMU: dcdc2 1100
[      0.886]PMU: cpux 1008 Mhz,AXI=336 Mhz
PLL6=600 Mhz,AHB1=200 Mhz, APB1=100Mhz AHB2=300Mhz MBus=400Mhz
device_type = 3253, onoff=1
dcdc1_vol = 3100, onoff=1
dcdc2_vol = 1100, onoff=1
dcdc6_vol = 1100, onoff=1
aldo1_vol = 2800, onoff=0
aldo2_vol = 1800, onoff=1
aldo3_vol = 3000, onoff=1
dldo1_vol = 3300, onoff=0
dldo2_vol = 3300, onoff=0
dldo3_vol = 2800, onoff=0
dldo4_vol = 3300, onoff=1
eldo1_vol = 1800, onoff=1
eldo2_vol = 1800, onoff=0
eldo3_vol = 1800, onoff=0
fldo2_vol = 1100, onoff=1
gpio0_vol = 3100, onoff=0
vbus not exist
normal dc exist, limit to dc
run key detect
no key found
no uart input
DRAM:  1008 MiB
fdt addr: 0x76ec23a0
Relocation Offset is: 35f14000
In:    serial
Out:   serial
Err:   serial
gic: sec monitor mode
[      1.192]start
drv_disp_init
init_clocks: finish init_clocks.
enable power vcc-hdmi-33, ret=0
drv_disp_init finish
boot_disp.output_disp=0
boot_disp.output_type=3
boot_disp.output_mode=5
fetch script data boot_disp.auto_hpd fail
disp0 device type(4) enable
attched ok, mgr0<-->device1, type=4, mode=5
[      1.600]end
workmode = 0,storage type = 1
[      1.604]MMC:	 0
[mmc]: @lex mmc driver ver 2015-06-03 13:50:00
sdc_no: 0
[mmc]: get card2_boot_para:sdc_ex_dly_used 0
[mmc]: delete mmc-hs400-1_8v from dtb
[mmc]: delete mmc-hs200-1_8v from dtb
[mmc]: delete mmc-ddr-1_8v from dtb
[mmc]: delete max-frequency from dtb
SUNXI@lex SD/MMC: 0
[mmc]: start mmc_calibrate_delay_unit, don't access device...
[mmc]: delay chain cal done, sample: 192(ps)
[mmc]: BPI: 0 CARD_TYPE_SD
[mmc]: media type 0x8000001
[mmc]: ************Try SD card 0************
[mmc]: host caps: 0x27
[mmc]: MID 03 PSN 112a425f
[mmc]: PNM ABLCD -- 0x41-42-4c-43-44
[mmc]: PRV 8.0
[mmc]: MDT m-11 y-2016
[mmc]: speed mode     : HSSDR52/SDR25 
[mmc]: clock          : 50000000 Hz
[mmc]: bus_width      : 4 bit
[mmc]: user capacity  : 30436 MB
[mmc]: ************SD/MMC 0 init OK!!!************
[mmc]: BPI: sunxi_switch_to_best_bus - host->mmc_no: 0 
[mmc]: erase_grp_size      : 0x1WrBlk*0x200=0x200 Byte
[mmc]: secure_feature      : 0x0
[mmc]: secure_removal_type : 0x0
[      1.955]sunxi flash init ok

** Unable to use mmc 0:1 for loading the env **
Using default environment

--------fastboot partitions--------
mbr not exist
base bootcmd=run mmcbootcmd
* storage_type=STORAGE_SD
bootcmd set setargs_mmc
key 0
recovery key high 12, low 10
fastboot key high 6, low 4
no misc partition is found
to be run cmd=run mmcbootcmd
update dtb dram start
update dtb dram  end
serial is: 1400503442182c0907ce
Detect: A64 model by DRAM size: 
A64 model: 2GB
PowerBus = 2(0: not exist 1:vBus 2:acBus 3:vBus&acBus)
Battery Voltage=0, Ratio=0
key trigger
sunxi_bmp_logo_display
** File not found bootlogo.bmp **
sunxi bmp info error : unable to open logo file bootlogo.bmp
[      2.258]inter uboot shell
Hit any key to stop autoboot:  1  0 
** File not found uEnv.txt **
** File not found boot.scr **
Booting with defaults ...
fdt ...
** File not found a64/a64.dtb **
libfdt fdt_check_header(): FDT_ERR_BADMAGIC
** File not found a64/Image **
sunxi#`

**Comment by avafinger** [comment]
Hmmm, looks like something wrong with your SD CARD.

Can you please check the file format of your SD CARD? attach the card to your PC HOST and type the following and print here the output like so:

```
alex@svn:/arm/ubuntu/nanopi-a64$ sudo fdisk -l /dev/sdc
[sudo] password for alex: 
Disk /dev/sdc: 3,7 GiB, 3951034368 bytes, 7716864 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0xd03ad961

Device     Boot  Start     End Sectors  Size Id Type
/dev/sdc1        40960  303103  262144  128M 83 Linux
/dev/sdc2       303104 7716863 7413760  3,5G 83 Linux
alex@svn:/arm/ubuntu/nanopi-a64$ ls -la /media/alex/
boot/   rootfs/ 
alex@svn:/arm/ubuntu/nanopi-a64$ ls -la /media/alex/boot/
total 1260
drwxr-xr-x  4 root root    4096 Out 12 20:25 .
drwxr-x---+ 4 root root    4096 Out 30 21:15 ..
drwxrwxrwx  2 root root    4096 Out 25 15:58 a64
-rw-r--r--  1 root root  144538 Jul 27 19:53 bootlogo.bmp
-rw-r--r--  1 root root       9 Out 12 21:27 Image.version
-rw-rw-r--  1 root root 1105192 Out 12 20:43 initrd.img
drwx------  2 root root   16384 Out 12 20:08 lost+found
-rw-r--r--  1 root root       0 Nov 15  2016 nanopi-a64.txt
-rw-r--r--  1 root root       0 Nov 18  2016 OV5640_SET.txt
-rw-r--r--  1 root root     175 Jan 27  2017 uEnv.txt
alex@svn:/arm/ubuntu/nanopi-a64$ ls -la /media/alex/boot/a64/
total 12232
drwxrwxrwx 2 root root     4096 Out 25 15:58 .
drwxr-xr-x 4 root root     4096 Out 12 20:25 ..
lrwxrwxrwx 1 root root       26 Out 24 15:32 a64.dtb -> nanopi-a64_720p_OV5640.dtb
lrwxrwxrwx 1 root root       20 Out 25 12:38 Image -> Image_3.10.105-a64-2
-rwxrwxr-x 1 alex alex 11867096 Out 25 12:31 Image_3.10.105-a64-2
-rw-rw-rw- 1 root root    68342 Out 25 12:29 nanopi-a64_1080p.dtb
-rw-rw-rw- 1 root root    82976 Out 13 18:55 nanopi-a64_1080p.dts
-rw-rw-rw- 1 root root    71162 Out 25 12:18 nanopi-a64_1080p_OV5640.dtb
-rw-rw-rw- 1 root root    86783 Out 25 11:55 nanopi-a64_1080p_OV5640.dts
-rw-rw-rw- 1 root root    71170 Out 25 12:29 nanopi-a64_720p.dtb
-rw-rw-rw- 1 root root    86751 Out 25 11:57 nanopi-a64_720p.dts
-rw-rw-rw- 1 root root    71158 Out 25 16:21 nanopi-a64_720p_OV5640.dtb
-rw-rw-rw- 1 root root    86790 Out 25 16:20 nanopi-a64_720p_OV5640.dts
alex@svn:/arm/ubuntu/nanopi-a64$ 

```

**Comment by explosive2005** [comment]
I think the problem might be with /dev/sdb2.

te-8300-SFF:~/Desktop/nanopi-a64-firmware-master$ sudo fdisk -l /dev/sdb
[sudo] password for peasy: 
Disk /dev/sdb: 29.7 GiB, 31914983424 bytes, 62333952 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x425fbd8f

Device     Boot  Start      End  Sectors  Size Id Type
/dev/sdb1        40960   303103   262144  128M 83 Linux
peasy@peasy-HP-Compaq-Elite-8300-SFF:~/Desktop/nanopi-a64-firmware-master$ ls -la /media/peasy
total 16
drwxr-x---+  4 root root 4096 Oct 30 18:19 .
drwxr-xr-x   3 root root 4096 Oct 25 16:54 ..
drwxr-xr-x   4 root root 4096 Oct 12 18:25 boot
drwxr-xr-x  21 root root 4096 Jul  4  2016 rootfs
peasy@peasy-HP-Compaq-Elite-8300-SFF:~/Desktop/nanopi-a64-firmware-master$ ls -la /media/peasy/boot/
total 1260
drwxr-xr-x  4 root root    4096 Oct 12 18:25 .
drwxr-x---+ 4 root root    4096 Oct 30 18:19 ..
drwxrwxrwx  2 root root    4096 Oct 25 12:58 a64
-rw-r--r--  1 root root  144538 Jul 27 17:53 bootlogo.bmp
-rw-r--r--  1 root root       9 Oct 12 19:27 Image.version
-rw-rw-r--  1 root root 1105192 Oct 12 18:43 initrd.img
drwx------  2 root root   16384 Oct 12 18:08 lost+found
-rw-r--r--  1 root root       0 Nov 15  2016 nanopi-a64.txt
-rw-r--r--  1 root root       0 Nov 18  2016 OV5640_SET.txt
-rw-r--r--  1 root root     175 Jan 27  2017 uEnv.txt
peasy@peasy-HP-Compaq-Elite-8300-SFF:~/Desktop/nanopi-a64-firmware-master$ ls -la /media/peasy/boot/a64/
total 12232
drwxrwxrwx 2 root  root      4096 Oct 25 12:58 .
drwxr-xr-x 4 root  root      4096 Oct 12 18:25 ..
lrwxrwxrwx 1 root  root        26 Oct 24 12:32 a64.dtb -> nanopi-a64_720p_OV5640.dtb
lrwxrwxrwx 1 root  root        20 Oct 25 09:38 Image -> Image_3.10.105-a64-2
-rwxrwxr-x 1 peasy peasy 11867096 Oct 25 09:31 Image_3.10.105-a64-2
-rw-rw-rw- 1 root  root     68342 Oct 25 09:29 nanopi-a64_1080p.dtb
-rw-rw-rw- 1 root  root     82976 Oct 13 16:55 nanopi-a64_1080p.dts
-rw-rw-rw- 1 root  root     71162 Oct 25 09:18 nanopi-a64_1080p_OV5640.dtb
-rw-rw-rw- 1 root  root     86783 Oct 25 08:55 nanopi-a64_1080p_OV5640.dts
-rw-rw-rw- 1 root  root     71170 Oct 25 09:29 nanopi-a64_720p.dtb
-rw-rw-rw- 1 root  root     86751 Oct 25 08:57 nanopi-a64_720p.dts
-rw-rw-rw- 1 root  root     71158 Oct 25 13:21 nanopi-a64_720p_OV5640.dtb
-rw-rw-rw- 1 root  root     86790 Oct 25 13:20 nanopi-a64_720p_OV5640.dts
peasy@peasy-HP-Compaq-Elite-8300-SFF:~/Desktop/nanopi-a64-firmware-master$

**Comment by explosive2005** [comment]
This might be easier to read.
```
peasy@peasy-HP-Compaq-Elite-8300-SFF:~/Desktop/nanopi-a64-firmware-master$ sudo fdisk -l /dev/sdb
[sudo] password for peasy: 
Disk /dev/sdb: 29.7 GiB, 31914983424 bytes, 62333952 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x425fbd8f

Device     Boot  Start      End  Sectors  Size Id Type
/dev/sdb1        40960   303103   262144  128M 83 Linux
peasy@peasy-HP-Compaq-Elite-8300-SFF:~/Desktop/nanopi-a64-firmware-master$ ls -la /media/peasy
total 16
drwxr-x---+  4 root root 4096 Oct 30 18:19 .
drwxr-xr-x   3 root root 4096 Oct 25 16:54 ..
drwxr-xr-x   4 root root 4096 Oct 12 18:25 boot
drwxr-xr-x  21 root root 4096 Jul  4  2016 rootfs
peasy@peasy-HP-Compaq-Elite-8300-SFF:~/Desktop/nanopi-a64-firmware-master$ ls -la /media/peasy/boot/
total 1260
drwxr-xr-x  4 root root    4096 Oct 12 18:25 .
drwxr-x---+ 4 root root    4096 Oct 30 18:19 ..
drwxrwxrwx  2 root root    4096 Oct 25 12:58 a64
-rw-r--r--  1 root root  144538 Jul 27 17:53 bootlogo.bmp
-rw-r--r--  1 root root       9 Oct 12 19:27 Image.version
-rw-rw-r--  1 root root 1105192 Oct 12 18:43 initrd.img
drwx------  2 root root   16384 Oct 12 18:08 lost+found
-rw-r--r--  1 root root       0 Nov 15  2016 nanopi-a64.txt
-rw-r--r--  1 root root       0 Nov 18  2016 OV5640_SET.txt
-rw-r--r--  1 root root     175 Jan 27  2017 uEnv.txt
peasy@peasy-HP-Compaq-Elite-8300-SFF:~/Desktop/nanopi-a64-firmware-master$ ls -la /media/peasy/boot/a64/
total 12232
drwxrwxrwx 2 root  root      4096 Oct 25 12:58 .
drwxr-xr-x 4 root  root      4096 Oct 12 18:25 ..
lrwxrwxrwx 1 root  root        26 Oct 24 12:32 a64.dtb -> nanopi-a64_720p_OV5640.dtb
lrwxrwxrwx 1 root  root        20 Oct 25 09:38 Image -> Image_3.10.105-a64-2
-rwxrwxr-x 1 peasy peasy 11867096 Oct 25 09:31 Image_3.10.105-a64-2
-rw-rw-rw- 1 root  root     68342 Oct 25 09:29 nanopi-a64_1080p.dtb
-rw-rw-rw- 1 root  root     82976 Oct 13 16:55 nanopi-a64_1080p.dts
-rw-rw-rw- 1 root  root     71162 Oct 25 09:18 nanopi-a64_1080p_OV5640.dtb
-rw-rw-rw- 1 root  root     86783 Oct 25 08:55 nanopi-a64_1080p_OV5640.dts
-rw-rw-rw- 1 root  root     71170 Oct 25 09:29 nanopi-a64_720p.dtb
-rw-rw-rw- 1 root  root     86751 Oct 25 08:57 nanopi-a64_720p.dts
-rw-rw-rw- 1 root  root     71158 Oct 25 13:21 nanopi-a64_720p_OV5640.dtb
-rw-rw-rw- 1 root  root     86790 Oct 25 13:20 nanopi-a64_720p_OV5640.dts
peasy@peasy-HP-Compaq-Elite-8300-SFF:~/Desktop/nanopi-a64-firmware-master$ ```

**Comment by avafinger** [comment]
Sure there is a problem with your sdcard, we should see two (2) partition and i don't see it or i overlooked it.

You should have sometinhg like this:

```
Device     Boot  Start     End Sectors  Size Id Type
/dev/sdb1        40960  303103  262144  128M 83 Linux
/dev/sdb2       303104 7716863 7413760  3,5G 83 Linux

```

Can you repeat the 
`sudo burn_sdcard_v2.sh /dev/sdb`

Maybe with another card also.

**Comment by explosive2005** [comment]
Okay, I can try another card.

**Comment by explosive2005** [comment]
Great job, it works. I had to use a different sd card reader. Which is strange because I can flash the Buildv1 image with my initial sd card reader. However, when booting the Buildv2 image, it displays 
```Press Enter for maintenance:```
It this typical?

**Comment by avafinger** [comment]
SD CARD reader can be really a nasty thing.
No it is not typical, i think you still have problems with your sdcard, maybe due to bad sdcard reader.
Most of the sdcard reader reset usb host in the middle of the writtings.. check your dmesg output while writing to sd card.
dmesg|tail while flashing will tell you something.

This message is on every boot?

**Comment by explosive2005** [comment]
Man i don't know what it is, but the sd card is working properly. I don't get any errors. Thanks for your hard work. I think this board will be great once you get spi working. Thanks.

**Comment by avafinger** [comment]
I've got a build with spi enabld but don't have a way to test ot.
Do you have a 2.8" spi tft lcd to check if it works?

**Comment by explosive2005** [comment]
Sorry I don't have a spi tft lcd, I was going to use the SPI for the nRF24L01+.

**Comment by avafinger** [comment]
ok then, i will update with a linux-image-kernel with SPI enabled, so you can give it a try. You may need to tweak DT for your device.

**Comment by explosive2005** [comment]
Ok I'll give it a try

**Comment by explosive2005** [comment]
Hey do you think you can upload the version that has SPI enabled?

**Comment by avafinger** [comment]
Will do in a couple of days.
